---
- name: Install English language pack
  apt:
    pkg={{ item }}
    state=present
  with_items:
  - language-pack-en-base

- name: Generate en_US.UTF-8
  command:
    locale-gen en_US.UTF-8

- name: Set default locale
  command:
    update-locale LANG=en_US.UTF-8 LC_MESSAGES=POSIX

